### ISSUE TITLE
any growl support in plans?

### ISSUE THREAD

**Issue by artemk** [jstorimer/spin#30]

**Comment by jstorimer** [comment]
I'm not a growl user myself. 

How do other projects handle this? Is there a standard way to integrate with growl or do all these libraries have to add growl knowledge to their internals?

**Comment by bittersweet** [comment]
Guard uses [ruby_gntp](https://rubygems.org/gems/ruby_gntp) for notifications.

In my opinion growl support is not really something for spin, because it's essentially a way to run TestUnit/Rspec faster. If you are running your tests manually you'll see your output already so I don't know what Growl has as an added benefit, it would only be useful if you have a really large/slow testsuite so you can do something else in the meantime.

So I would advice to just use [guard-spin](https://github.com/vizjerai/guard-spin) if you want growl support :)

**Comment by artemk** [comment]
@bittersweet guard-spin doesn't use growl for notifications.

**Comment by bittersweet** [comment]
Yes but in my opinion growl support should be added there and not in the main project.

**Comment by artemk** [comment]
i don't see why it should be added into guard-spin but not into spin itself. spin can be used without guard, and itself should support growl.

**Comment by bittersweet** [comment]
The fact is that spin doesn't really know or care about the test output. So it would be hard to generate useful growl notifications. So my point was that this would be solved better via a rspec formatted for example.

**Comment by artemk** [comment]
green or red notification would be enough. spin does know about success or failure result.

**Comment by jstorimer** [comment]
If you want formatted output then there are gems that will do this for you. It won't be added to spin, but spin should work fine alongside them.

I also don't see a compelling reason to add growl support. Closing for now.
